### PR TITLE
enhancements[refresh,upnp up now]

### PR DESCRIPTION
**Pull request by jredfox**
adds methods: 
refresh (refreshes the gatewayfinder and gateway to new objects)
upnp (a dangerous check for is upnp open at this ms)

I have a basic implementation of your library here if you wanted to update your readme file on how to use this library for other people. Note that the add schudule is minecraft specific since if it fails to port once then it refreshes UPnP when user re-opens to internet again else it doesn't refresh. 
https://github.com/jredfox/lanessentials/blob/master/src/main/java/com/EvilNotch/lanessentials/LanUtil.java

I used these in lan-essentials and thought it would be helpful

### CODE REVIEW

**Comment by adolfintel** [comment]
I'm not sure I understand the point of this? Your users move from a network to another while running minecraft?

**Comment by jredfox** [comment]
No it's when your offline and you try and open to lan it fails so you save and quit go back in online and your UPnP gateway needed a refresh to tell it it's online again. Since isUPnPUpNow() is up now is always going to say false the first time I have a boolean for hasPorted to check is it the first time.

**Comment by adolfintel** [comment]
Here's an idea: why don't we add a thread that automatically runs this refresh? And maybe automatically transfer the port mappings when a change is detected?

**Comment by jredfox** [comment]
Will the refresh cause any issues or take a while to respond? How often will it check for if it needs a refresh? I don't know could be better it's your library.

Maybe if the UPNP is up now returns false and the gateway finder isn't searching and it isn't currently refreshing call the refresh? I guess syncing any port mappings if any would be a good idea but, I am not familiar with everything that would need to be done so could you handle this?

**Comment by adolfintel** [comment]
Discovery usually takes a few seconds. Let's say every 1 minute?

**Comment by jredfox** [comment]
I will let you handle it then. You can close this and use what is valuable to you in this pull.

 I made a separate thread in the one method so minecraft doesn't freeze while you wait for your port to be open. 

I also noticed it constantly calls UPnP.isUnPAvailible() when that takes alot of ms *after* the first time. Could you maybe optimize it or no?

**Comment by jredfox** [comment]
I think just randomly checking every minuet might be good for your lib to refresh but, as for mc I think it should try and refresh if necessary whenever the port forward button has been clicked. Especially since internet could come back before a minuet is up. 

Again it's your lib your choice thanks

**Comment by adolfintel** [comment]
Yes, it could be improved, after all this is something that I came up in a few hours, it's not a super sophisticated thing, it was never even updated before you noticed that bug about closing TCP ports.

**Comment by jredfox** [comment]
so it's up to the client's implementations to keep the ports up in my opinion since they are going to use server sockets. Aka if the client's program doesn't have toLan() support they need to create it first before instantiating port forwarding and refresh the toLan() on their own. Minecraft already does this on both lan and dedicated lan servers

The refresh method I renamed to refreshProgram() to ensure people it's not going to refresh ports. I only use it when the program fails to initially first instantiate to find gateways.

I am going to give it a go and try and optimize it so port opens in < 1 second but, **I would prefer if you would do it on your end first so I don't break stuffs**

Also this library only seems to support UPNP? What about NAT-PMP and newer popular protocol could you add support for them please so your library is more compatible on all routers?

**Comment by adolfintel** [comment]
I don't know other protocols well enough to add support.
Feel free to make all the changes you want, this isn't some big project, it's something I wrote in a few hours in 2015 and never updated.

**Comment by jredfox** [comment]
Well can you learn them no rush but, I would like to see it happen thanks. I know nothing of any protocols that's when I found your lib. I have two massive coding projects and college soon so I don't have time to learn deep in networking and compatibility just enough to use a lib.

**Comment by jredfox** [comment]
I found an interesting article about all three protocols but, I don't know how to translate it to java.

**Comment by jredfox** [comment]
I am so sorry I thought I sent you it but, apparently it didn't save the edit:
https://tools.ietf.org/id/draft-bpw-pcp-upnp-igd-interworking-01.html
https://tools.ietf.org/html/rfc6886

Also I know this isn't your project but, it looks like it supports all three protocols not just one. The issue with that program is it doesn't dynamically get the ips it needs to function. So if you want to figure out NAT-PMP and PCP by itself and maybe copy some code here is the place to do it.
https://github.com/offbynull/portmapper

**Comment by jredfox** [comment]
new pull request has everything

**Pull request closed without merging**
